name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      # Setup python for cfn cli
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      # Install pip and cfn cli
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudformation-cli-go-plugin

      # Setup go 1.17
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17.x

      # Make the package from Makefile.package
      - name: Make package
        run: GOPROXY=direct make -f Makefile.package package

      # Get the release notes from CHANGELOG.md
      - name: Extract release notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v1

      # Create the release with tag name and packages
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.extract_release_notes.outputs.release_notes }}
          files: |
            awsqs-kubernetes-helm.zip
            register-type.template.yaml
            execution-role.template.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

